### ISSUE TITLE
3.0.0 doesn't send function names in backtraces

### ISSUE THREAD

**Issue by cap10morgan** [bmabey/clj-airbrake#25]
Below is an example of a 2.4.3-sent backtrace:

<img width="503" alt="screen shot 2016-03-05 at 11 34 06 am" src="https://cloud.githubusercontent.com/assets/59748/13549590/4c737292-e2c6-11e5-95e3-73c18dceacda.png">

And this is the same exception sent by 3.0.0:

<img width="298" alt="screen shot 2016-03-05 at 11 34 27 am" src="https://cloud.githubusercontent.com/assets/59748/13549588/430e12ac-e2c6-11e5-857c-e1a740391383.png">

**Comment by bmabey** [comment]
@firthh any chance you could take a look at this?
I'm not using this project anymore and so I'm not terribly motivated to spend much time on it.

**Comment by cap10morgan** [comment]
Looks good in 3.0.1. Thanks!
