### ISSUE TITLE
Error type gets entire entire error message in 3.0.0

### ISSUE THREAD

**Issue by cap10morgan** [bmabey/clj-airbrake#26]
Below is a screenshot of a 2.4.3-sent exception (notice the "Error type" value):

<img width="926" alt="screen shot 2016-03-05 at 11 37 40 am" src="https://cloud.githubusercontent.com/assets/59748/13549611/bc56d39c-e2c6-11e5-81cb-6bd46b4e63b0.png">

And here is the same exception sent by 3.0.0 (notice "Error type" repeats the entire "Error message" value):

<img width="934" alt="screen shot 2016-03-05 at 11 38 58 am" src="https://cloud.githubusercontent.com/assets/59748/13549620/e1727f82-e2c6-11e5-973b-40fb62657990.png">

**Comment by bmabey** [comment]
@firthh if you do take a look there is this issue as well...

**Comment by firthh** [comment]
@bmabey I'll try to take a look this afternoon

**Comment by bmabey** [comment]
@cap10morgan I just merged in a fix from @firthh and released it as `v3.0.1`.

**Comment by bmabey** [comment]
@cap10morgan could you verify that the fix works for you?

**Comment by cap10morgan** [comment]
@bmabey Yes, I'll try it again today. Thanks to you and @firthh!

**Comment by cap10morgan** [comment]
They now all start with `class` which seems extraneous since it will never change (right?). But other than that, looks good to me.

**Comment by firthh** [comment]
@cap10morgan I hadn't actually noticed the `class` there. I've commited a change that should get rid of that. I'll submit another pull request to get it merged in
