### ISSUE TITLE
Calling clj-airbrake within callback from HTTP-kit request can result in a deadlock

### ISSUE THREAD

**Issue by firthh** [bmabey/clj-airbrake#30]
It looks like the HTTP-kit client has a [threadpool](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L86) to serve callbacks from requests.

This means if you try to call out to airbrake within a callback you can end up in a deadlock situation.

For example this _can_ result in a deadlock if the endpoint that will result in errors:
```clojure
(take
 1000
 (repeatedly
  #(http/get "http://host.com/path" options
             (fn [{:keys [status headers body error]}] ;; asynchronous response handling
               (if error
                 (airbrake/notify {:config :config} error)
                 (println "Async HTTP GET: " status))))))
```

The main solution I'm considering is to replace `http-kit` with `clj-http-lite`. The goal would be to give the caller more flexibility with the choice of asynchronous mechanisms and even http library. Part of this I would like to deprecating the function `notify-async` and the implementation for it will call `notify` within a future.

Please let me know if anyone has feedback.

**Comment by bmabey** [comment]
The main motivation for bringing in `http-kit` was to allow for async calls, see #13, so I would like to have a decent solution for that out of the box. Using a future out of clojure's built-in-thread pool doesn't seem like a horrible idea but you seem to be arguing for deprecating that functionality completely. This kind of deadlocking must happen in other use cases of `http-kit`... do you know if they provide a way to pass a priority to a request (so we can push the Airbrake ones down in priority).

  With your proposal/patch how do you give the caller flexibility on the choice of HTTP library?

**Comment by firthh** [comment]
Sorry, I hadn't realised there had been a request specifically for asynchronous calls. Happy to not deprecate the async call.

As far as I can tell with http-kit, it's possible for airbrake to pass an alternate threadpool for it to use. Which is another possible solution, I hadn't thought of until I dug a little more into http-kit today. Probably a better first step, keep everything as is and stop the deadlocking from being possible.

The patch at the moment doesn't give the caller the flexibility to choose the HTTP library, still working on that side of things.

**Comment by bmabey** [comment]
"Probably a better first step, keep everything as is and stop the deadlocking from being possible."

So are you suggesting to keep `http-kit` and use a separate threadpool?

**Comment by firthh** [comment]
Yeah, that's what I suggest, I'm trying to get that working now.

I still like the idea of pushing back the asynchronous mechanism to the code calling the library. That way they can choose to use core.async, a future, aleph, http-kit (with callbacks), or whatever other mechanism they choose. But that's a bigger change...
